apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
spec:
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: http
    port: 80
    protocol: HTTP
  - name: https-1
    protocol: HTTPS
    port: 443
    hostname: "*"
    tls:
      certificateRefs:
      - kind: Secret
        name: local-ca


