apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml
- project.yaml
- app.yaml
- route.yaml

patches:
  - patch: |-
      kind: not-important
      metadata:
        name: not-important
      spec:
        template:
          spec:
            tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
    target:
      kind: (StatefulSet|Deployment|Job)

configMapGenerator:
- name: argocd-cmd-params-cm
  behavior: merge
  literals:
  - server.insecure=true
- name: argocd-cm
  behavior: merge
  literals:
  - url=https://argocd-new.local.ongy.net
  files:
  - resource.exclusions=cilium-exclusions
  - oidc.config=oidc-config


