apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  annotations:
    external-dns.alpha.kubernetes.io/hostname: argocd-new.local.ongy.net.
spec:
  parentRefs:
  - name: gateway
    namespace: kube-system
  hostnames:
  - "argocd.local.ongy.net"
  - "argocd-new.local.ongy.net"
  rules:
  - backendRefs:
    - name: argocd-server
      port: 80
