apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
spec:
  parentRefs:
  - name: gateway
    namespace: kube-system
  hostnames:
  - "argocd.local.ongy.net"
  rules:
  - backendRefs:
    - name: argocd-server
      port: 80
